#!/bin/bash

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PATH=/opt/anaconda/anaconda-python-3.7/bin:$PATH

if [ -e "$basedir/pyenv/version" ]; then
    python_version=$(<$basedir/pyenv/version)
fi
# Create Python environment based on Anaconda
echo $python_version
conda create --prefix $basedir/.user/pyenv --yes --copy --no-default-packages python==$python_version
source activate $basedir/.user/pyenv
if [ -e "$basedir/pyenv/conda.txt" ]; then
    conda install --copy --file=$basedir/pyenv/conda.txt
fi
conda update --yes --copy
pip install --upgrade pip
if [ -e "$basedir/pyenv/requirements.txt" ]; then
    pip install -r $basedir/pyenv/requirements.txt
fi

if [ -e "$basedir/node/package.json" ]; then
    cd "$basedir/node" && npm install && cd -
fi

export HISTFILE=$basedir/.user/history
history -c

if [ -e "$HISTFILE" ]; then
    history -r $HISTFILE
fi

if [ -e "$basedir/history" ]; then
    history -r $basedir/history
fi

export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \W \$\[\033[00m\] '
alias inv="inv --search-root=$basedir/pyenv/invoke"
cd ./source

export COMPOSE_PROJECT_NAME=gch-nn
export COMPOSE_FILE=$PWD/docker-compose/nn.yaml

clear